allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - ws@8.20.1
  - sharp@0.35.0
  - brace-expansion@5.0.8
overrides:
  brace-expansion@<=5.0.7: ^5.0.8
  sharp@<0.35.0: ^0.35.0
  ws@>=8.0.0 <8.20.1: ^8.20.1
