onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp

overrides:
  brace-expansion@<5.0.5: '>=5.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  uuid@<14.0.0: '>=14.0.0'
